### ISSUE TITLE
Numbering of tickets

### ISSUE THREAD

**Issue by arirawr** [djeik/hacksignal#7]
Do tickets have numbers? Would this be better than email for identifying chatlogs? 

Use case:
- Each email and/or username could open multiple tickets and eventually view them
- Rooms could stay open event.url.tld/ticketnumber and email/username could be used to view

**Comment by tsani** [comment]
Tickets are all given unique identifiers (in the form of sequential numbers). Right now, the chat system is on a per-email basis (the tokens we use are based on email addresses). However, nothing's stopping us from doing it on a per-ticket basis; IMO that makes more sense honestly.
